# Matrix Algebra
---
**Name:** Jonh Alexis Buot <br>
**Date:** December 2023 <br>
**Course:** CS3101N <br>
**Task:** Assignment - Matrix Algebra

---

In [1]:
import numpy as np

# Code Challenges

For the coding challenges, sample executions would be shown, as well as `numpy` executions to compare the results of the two.

**1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.**

In [2]:
def matrix_add(A, B):
# =============================================================================
#   Performs matrix addition on 2 numpy matrices: A and B.
# =============================================================================
    assert len(A.shape) == 2, "A must be a matrix (2D numpy array.)"
    assert len(B.shape) == 2, "B must be a matrix (2D numpy array.)"
    assert A.shape == B.shape, "Matrices must be of the same shape."

    m = A.shape[0]
    n = A.shape[1]

    sum = np.copy(A).astype("float64")
    
    for i in range(m):
        for j in range(n):
            sum[i][j] += B[i][j]

    return sum

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")
B = np.random.randint(-50, 50, size=(5, 4)).astype("float64")

my_result = matrix_add(A, B)
np_result = A + B

print("-- A --", A, sep="\n")
print("\n-- B --", B, sep="\n")
print("\n-- My A + B --", my_result, sep="\n")
print("\n-- Numpy A + B --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[-49.  30.  43.  -9.]
 [ 24. -10.  44.  42.]
 [  9. -19.  -8. -19.]
 [ -8. -12. -43. -27.]
 [ 22. -22. -35. -50.]]

-- B --
[[-26.  -9.  14.  -7.]
 [-18. -39.   8.  -8.]
 [ 19.   0.  -3.  -1.]
 [-24. -48.  14.  26.]
 [-13. -35. -46. -46.]]

-- My A + B --
[[-75.  21.  57. -16.]
 [  6. -49.  52.  34.]
 [ 28. -19. -11. -20.]
 [-32. -60. -29.  -1.]
 [  9. -57. -81. -96.]]

-- Numpy A + B --
[[-75.  21.  57. -16.]
 [  6. -49.  52.  34.]
 [ 28. -19. -11. -20.]
 [-32. -60. -29.  -1.]
 [  9. -57. -81. -96.]]

Are my results equal to numpy? Yes.


**2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.**

In [3]:
def matrix_multiply(A, B):
# =============================================================================
#   Performs matrix multiplication on 2 numpy matrices: A and B.
# =============================================================================
    assert len(A.shape) == 2, "A must be a matrix (2D numpy array.)"
    assert len(B.shape) == 2, "B must be a matrix (2D numpy array.)"
    # A = m x s, B = s x n
    assert A.shape[1] == B.shape[0], "Columns of Matrix A must equal rows of matrix B."

    m = A.shape[0]
    s = A.shape[1]
    n = B.shape[1]

    product = np.empty((m, n), dtype="float64")

    for i in range(m):
        for j in range(n):
            product[i][j] = sum(A[i][k] * B[k][j] for k in range(s))

    return product

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")
B = np.random.randint(-50, 50, size=(4, 5)).astype("float64")

my_result = matrix_multiply(A, B)
np_result = np.matmul(A, B)

print("-- A --", A, sep="\n")
print("\n-- B --", B, sep="\n")
print("\n-- My A * B --", my_result, sep="\n")
print("\n-- Numpy A * B --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[ 47.  33.   6.  48.]
 [ 28. -19. -42. -33.]
 [ 34. -35. -36. -48.]
 [-50.  -4. -29.  17.]
 [ -6.  -4.  40. -38.]]

-- B --
[[-14.  13. -37.  21. -24.]
 [-50. -32.  22.  -4. -24.]
 [ 29. -31.   1.  47. -12.]
 [ 30.  30. -14.   3.  38.]]

-- My A * B --
[[ -694.   809. -1679.  1281.  -168.]
 [-1650.  1284. -1034. -1409.  -966.]
 [-1210.  1238. -1392.  -982. -1368.]
 [  569.   887.  1495. -2346.  2290.]
 [  304. -2330.   706.  1656. -1684.]]

-- Numpy A * B --
[[ -694.   809. -1679.  1281.  -168.]
 [-1650.  1284. -1034. -1409.  -966.]
 [-1210.  1238. -1392.  -982. -1368.]
 [  569.   887.  1495. -2346.  2290.]
 [  304. -2330.   706.  1656. -1684.]]

Are my results equal to numpy? Yes.


**3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.**

In [4]:
def matrix_scale(A, k):
# =============================================================================
#   Performs scalar multiplication on a numpy matrix A.
# =============================================================================
    assert len(A.shape) == 2, "A must be a matrix (2D numpy array.)"

    m = A.shape[0]
    n = A.shape[1]

    scaled = np.copy(A).astype("float64")

    for i in range(m):
        for j in range(n):
            scaled[i][j] *= k

    return scaled

A = np.random.randint(-50, 50, size=(4, 3)).astype("float64")
B = np.random.randint(-50, 50, size=(4, 3)).astype("float64")
k = np.random.randint(-10, 10)

# k(A + B)
scalar_multiply_sum = matrix_scale(matrix_add(A, B), k)

# kA + kB
scalar_multiply_matrices_then_sum = matrix_add(matrix_scale(A, k), matrix_scale(B, k))

print("-- k --", k, sep="\n")
print("\n-- A --", A, sep="\n")
print("\n-- B --", B, sep="\n")
print("\n-- k(A + B) --", scalar_multiply_sum, sep="\n")
print("\n-- kA + kB --", scalar_multiply_matrices_then_sum, sep="\n")
print("\nAre the results equal?", "Yes." if (scalar_multiply_matrices_then_sum == scalar_multiply_sum).all() else "No.")

-- k --
-9

-- A --
[[ 36. -24.  21.]
 [-18.  -3. -45.]
 [  0.  13. -13.]
 [-49. -37.   1.]]

-- B --
[[-46. -49. -16.]
 [ 21. -39. -43.]
 [-30.  29.   1.]
 [ 18.  39.  16.]]

-- k(A + B) --
[[  90.  657.  -45.]
 [ -27.  378.  792.]
 [ 270. -378.  108.]
 [ 279.  -18. -153.]]

-- kA + kB --
[[  90.  657.  -45.]
 [ -27.  378.  792.]
 [ 270. -378.  108.]
 [ 279.  -18. -153.]]

Are the results equal? Yes.


**4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.**

In [5]:
def matrix_diag(A):
# =============================================================================
#   Get the diagonal of a numpy matrix A.
# =============================================================================
    assert len(A.shape) == 2, "A must be a matrix (2D numpy array.)"

    n = min(A.shape)
    return np.array([A[i][i] for i in range(n)]).astype("float64")

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")

my_result = matrix_diag(A)
np_result = np.diag(A)

print("-- A --", A, sep="\n")
print("\n-- My diag(A) --", my_result, sep="\n")
print("\n-- Numpy diag(A) --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[ 42.  15.  27.   7.]
 [ 22.  47. -12. -20.]
 [ -8.  19.  15.  46.]
 [ 13. -37. -29.   5.]
 [-16. -49.  27.  -2.]]

-- My diag(A) --
[42. 47. 15.  5.]

-- Numpy diag(A) --
[42. 47. 15.  5.]

Are my results equal to numpy? Yes.


**5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.**

In [6]:
def matrix_trace(A):
# =============================================================================
#   Get the trace of a numpy matrix A.
# =============================================================================
    assert len(A.shape) == 2, "A must be a matrix (2D numpy array.)"
    
    n = min(A.shape)
    return sum(A[i][i] for i in range(n))

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")

my_result = matrix_trace(A)
np_result = np.trace(A)

print("-- A --", A, sep="\n")
print("\n-- My tr(A) --", my_result, sep="\n")
print("\n-- Numpy tr(A) --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[-37.   2. -16.   9.]
 [-40.  16.  12. -14.]
 [ 13.  44.  -4.  14.]
 [  4. -16.   4.  20.]
 [-30. -37.  46.  16.]]

-- My tr(A) --
-5.0

-- Numpy tr(A) --
-5.0

Are my results equal to numpy? Yes.


# Problem Solving

**1. Solve $\textbf{X}$ given that:**
$
\begin{align}
    \textbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix},\ 
    \textbf{B} = \begin{bmatrix} -1 & 0 \\ 1 & 1 \end{bmatrix} 
\end{align}
$

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])

- $3\mathbf{X} = \mathbf{A} - 2\mathbf{B}$

**Manual Solution**

$$
\begin{align}
    3\textbf{X} &= \textbf{A} - 2\textbf{B} \\
    \frac{1}{\cancel{3}}\cancel{3}\textbf{X} &= \frac{1}{3}(\textbf{A} - 2\textbf{B}) \\
    \textbf{X} &= \frac{1}{3}(\textbf{A} - 2\textbf{B}) \\
        &= \frac{1}{3}\begin{pmatrix}\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} - 2\begin{bmatrix} -1 & 0 \\ 1 & 1 \end{bmatrix} \end{pmatrix} \\
        &= \frac{1}{3}\begin{pmatrix}\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} - \begin{bmatrix} -2 & 0 \\ 2 & 2 \end{bmatrix} \end{pmatrix} \\
        &= \frac{1}{3}\begin{bmatrix} 3 & 2 \\ 1 & 2 \end{bmatrix} \\
    \textbf{X} &= \boxed{\begin{bmatrix} 1 & \frac{2}{3} \\ \frac{1}{3} & \frac{2}{3} \end{bmatrix}}
\end{align}
$$

**Pythonic Solution**

In [8]:
X = (A - 2 * B) / 3     # eq. 3
X

array([[1.        , 0.66666667],
       [0.33333333, 0.66666667]])

- $2(\textbf{A} - \textbf{B} + 2\textbf{X}) = 3(\textbf{X} - \textbf{B})$

**Manual Solution**

$$
\begin{align}
    2(\textbf{A} - \textbf{B} + 2\textbf{X}) &= 3(\textbf{X} - \textbf{B}) \\
    2\textbf{A} - 2\textbf{B} + 4\textbf{X} &= 3\textbf{X} - 3\textbf{B} \\
    4\textbf{X} - 3\textbf{X} &= 2\textbf{B} - 3\textbf{B} - 2\textbf{A}  \\
    \textbf{X} &= - \textbf{B} - 2\textbf{A}  \\
        &= - \begin{bmatrix} -1 & 0 \\ 1 & 1 \end{bmatrix} - 2\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}  \\
        &= \begin{bmatrix} 1 & 0 \\ -1 & -1 \end{bmatrix} - \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}  \\
    \textbf{X} &= \boxed{\begin{bmatrix} -1 & -4 \\ -7 & -9 \end{bmatrix}}
\end{align}
$$

**Pythonic Solution**

In [9]:
X = (-B - 2 * A)    # eq. 4
X

array([[-1, -4],
       [-7, -9]])

**2. Write $\textbf{B}$ as a linear combination of the other matrices, if possible.**

For checking purposes the function declared below, `reduced_row_echelon_form` will be used to verify solutions.

In [10]:
def reduced_row_echelon_form(matrix, augment_size = 1):
# =============================================================================
#   Transforms a given matrix into its reduced row echelon form.
#   Additionally, this returns a tuple containing the RRFE, and
#   the solution vector, if the augment size is supplied with a
#   non-zero value.
# =============================================================================
    assert len(matrix.shape) == 2, "A must be a matrix (2D numpy array.)"
    assert augment_size >= 0, "Augment size must be equal to zero or a positive number."

    matrix = np.copy(matrix).astype("float64")
    m, n = matrix.shape
    n -= augment_size

    for i in range(min(m, n)):
        pivot_row = i
        while pivot_row < m and matrix[pivot_row, i] == 0:  # Get the row of the leading entry of the column
            pivot_row += 1

        if pivot_row == m:                                  # Skip zero columns
            continue
        
        matrix[[i, pivot_row]] = matrix[[pivot_row, i]]     # Put pivot row at the correct position 
        matrix[i] /= matrix[i, i]                           # Leading entry = 1

        # Eliminate other elements in the current column
        for j in range(m):
            if j == i: continue
            matrix[j] -= matrix[i] * matrix[j, i]

    # Remove 0 = 0 rows
    zero_rows = np.all(matrix == 0, axis=1)
    matrix, zero_matrix = matrix[~zero_rows], matrix[zero_rows]
    rref = np.concatenate([matrix, zero_matrix])

    if augment_size != 0 and any(np.all(matrix[:, :-augment_size] == 0, axis=1)):      # Check for 0 == N rows
        return rref, None
    elif m < n:                                                  # Check for infinite solutions
        return rref, np.inf 

    return rref, matrix[:, -augment_size:]

- 
$
\begin{align}
    \textbf{A}_1 = \begin{bmatrix} 1 & 2 \\ -1 & 1 \end{bmatrix},\
    \textbf{A}_2 = \begin{bmatrix} 0 & 1 \\  2 & 1 \end{bmatrix},\
    \textbf{B} = \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$

**Manual Solution**

Transform the matrices into a linear equation of the form $\textbf{A}_1x + \textbf{A}_2y = \textbf{B}$, where $x, y \in \mathbb{R}$. By substitution, we have the following:
$
\begin{align}
    \begin{bmatrix} 1 & 2 \\ -1 & 1 \end{bmatrix}x +
    \begin{bmatrix} 0 & 1 \\  2 & 1 \end{bmatrix}y =
    \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$
$ 
\begin{align}
    \begin{bmatrix} x & 2x \\ -x & x \end{bmatrix} +
    \begin{bmatrix} 0 & y \\  2y & y \end{bmatrix} =
    \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$
$ 
\begin{align}
    \begin{bmatrix} x & 2x + y \\ -x + 2y & x + y \end{bmatrix} =
    \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$
The simplified expression can be translated into a system of linear equations.
$$
\begin{align}
    x &= 2 \\
    2x + y &= 5 \\
    -x + 2y &= 0 \\
    x + y &= 3
\end{align}
$$
This system of linear equation can then be transformed into an `augmented matrix`.
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        2 & 1 &\bigm| & 5 \\
        -1 & 2 &\bigm| & 0 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
\end{align}
$
Perform row operations to reduce it to reduced row echelon form.
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        2 & 1 &\bigm| & 5 \\
        -1 & 2 &\bigm| & 0 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 + \textbf{R}_1}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        2 & 1 &\bigm| & 5 \\
        0 & 2 &\bigm| & 2 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        2 & 1 &\bigm| & 5 \\
        0 & 2 &\bigm| & 2 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
    \xrightarrow{\frac{1}{2}\textbf{R}_3}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        2 & 1 &\bigm| & 5 \\
        0 & 1 &\bigm| & 1 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        2 & 1 &\bigm| & 5 \\
        0 & 1 &\bigm| & 1 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 \leftrightarrow \textbf{R}_3}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        2 & 1 &\bigm| & 5 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        2 & 1 &\bigm| & 5 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 - 2\textbf{R}_4}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & -1 &\bigm| & -1 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & -1 &\bigm| & -1 \\
        1 & 1 &\bigm| & 3 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_4 + \textbf{R}_3}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & -1 &\bigm| & -1 \\
        1 & 0 &\bigm| & 2 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & -1 &\bigm| & -1 \\
        1 & 0 &\bigm| & 2 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_4 - \textbf{R}_1}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & -1 &\bigm| & -1 \\
        0 & 0 &\bigm| & 0 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & -1 &\bigm| & -1 \\
        0 & 0 &\bigm| & 0 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 + \textbf{R}_2}
    \begin{bmatrix}
        1 & 0 &\bigm| & 2 \\
        0 & 1 &\bigm| & 1 \\
        0 & 0 &\bigm| & 0 \\
        0 & 0 &\bigm| & 0 \\
    \end{bmatrix}
\end{align}
$

From the reduced row echelon, it can be seen that the solutions to our linear equation are $x = 2$, and $y = 1$.

$\boxed{\therefore \textbf{B} \text{ can be expressed as a linear combination of } \textbf{A}_1 \text{ and } \textbf{A}_2 \text{ through a linear equation of the form } \textbf{B} = 2\textbf{A}_1 + \textbf{A}_2}$.

**Pythonic Solution**

In [11]:
A = np.array([[1, 0, 2],
              [2, 1, 5],
              [-1, 2, 0],
              [1, 1, 3]])

rref, solution = reduced_row_echelon_form(A)
print("-- Reduced Row Echelon Form --", rref, sep="\n")
print("\n-- Solution --", solution, sep="\n")
print(f"\nx = {solution[0][0]}", f"y = {solution[1][0]}", sep=", ")

-- Reduced Row Echelon Form --
[[1. 0. 2.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

-- Solution --
[[2.]
 [1.]]

x = 2.0, y = 1.0


-
$
\begin{align}
    \textbf{A}_1 = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix},\
    \textbf{A}_2 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix},\
    \textbf{A}_3 = \begin{bmatrix} 1 & -1 \\ 1 & 1 \end{bmatrix},\
    \textbf{B} = \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$

**Manual Solution**

Transform the matrices into a linear equation of the form $\textbf{A}_1x + \textbf{A}_2y + \textbf{A}_3z = \textbf{B}$, where $x, y, z \in \mathbb{R}$. By substitution, we have the following:
$
\begin{align}
    \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}x +
    \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}y +
    \begin{bmatrix} 1 & -1 \\ 1 & 1 \end{bmatrix}z =
    \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix} x & 0 \\ 0 & x \end{bmatrix} +
    \begin{bmatrix} 0 & y \\ y & 0 \end{bmatrix} +
    \begin{bmatrix} z & -z \\ z & z \end{bmatrix} =
    \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$
$
\begin{align}   
    \begin{bmatrix} x + z & y - z \\ y + z & x + z \end{bmatrix} =
    \begin{bmatrix} 2 & 5 \\  0 & 3 \end{bmatrix}
\end{align}
$
The simplified expression can be translated into a system of linear equations.
$$
\begin{align}
    x + z &= 2 \\
    y - z &= 5 \\
    y + z &= 0 \\
    x + z &= 3
\end{align}
$$
This system of linear equation can then be transformed into an `augmented matrix`.
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &  1 &\bigm| & 2 \\
        0 & 1 & -1 &\bigm| & 5 \\
        0 & 1 &  1 &\bigm| & 0 \\
        1 & 0 &  1 &\bigm| & 3 \\
    \end{bmatrix}
\end{align}
$
Perform row operations to reduce it to reduced row echelon form.
$
\begin{align}
    \begin{bmatrix}
        1 & 0 &  1 &\bigm| & 2 \\
        0 & 1 & -1 &\bigm| & 5 \\
        0 & 1 &  1 &\bigm| & 0 \\
        1 & 0 &  1 &\bigm| & 3 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_4 - \textbf{R}_1}
    \begin{bmatrix}
        1 & 0 &  1 &\bigm| & 2 \\
        0 & 1 & -1 &\bigm| & 5 \\
        0 & 1 &  1 &\bigm| & 0 \\
        0 & 0 &  0 &\bigm| & 1 \\
    \end{bmatrix}
\end{align}
$
Looking at the last row yields $0x + 0y + 0z != 1$ which means this system of linear equations is inconsistent, thus yields no solutions.

$\boxed{\therefore \textbf{B} \text{ can't be expressed as a linear combination of } \textbf{A}_1 \text{ and } \textbf{A}_2}$.

**Pythonic Solution**

In [12]:
A = np.array([[1, 0, 1, 2],
              [0, 1, -1, 5],
              [0, 1, 1, 0],
              [1, 0, 1, 3]])

rref, solution = reduced_row_echelon_form(A)
print("-- Reduced Row Echelon Form --", rref, sep="\n")
print("\n-- Solution --", solution, sep="\n")

-- Reduced Row Echelon Form --
[[ 1.   0.   0.   4.5]
 [ 0.   1.   0.   2.5]
 [ 0.   0.   1.  -2.5]
 [ 0.   0.   0.   1. ]]

-- Solution --
None


**3. Given the following:**
$
\begin{align}
    \textbf{A} = \begin{bmatrix} 1 & 2 \\ 2 & 6 \end{bmatrix},\
    \textbf{b}_1 = \begin{bmatrix} 3 \\ 5 \end{bmatrix},\
    \textbf{b}_2 = \begin{bmatrix} -1 \\ 2 \end{bmatrix},\
    \textbf{b}_3 = \begin{bmatrix} 2 \\ 0 \end{bmatrix}
\end{align}
$

In [13]:
A = np.array([[1, 2], [2, 6]])
b_1 = np.array([[3], [5]])
b_2 = np.array([[-1], [2]])
b_3 = np.array([[2], [0]])

- Find $\textbf{A}^{-1}$, and use this to solve $\textbf{A}x = b_1$, $\textbf{A}x = b_2$, and $\textbf{A}x = b_3$

**Manual Solution**

Given the following.
$$
\begin{align}
    \textbf{A} = \begin{bmatrix} 1 & 2 \\ 2 & 6 \end{bmatrix} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
\end{align}
$$
We can find the value of $\textbf{A}^{-1}$ through the following formula.
$$
\begin{align}
    \textbf{A}^{-1} &= \frac{1}{ad - bc}\begin{bmatrix} d & -b \\ -c & a \end{bmatrix} \\
        &= \frac{1}{(1)(6) - (2)(2)}\begin{bmatrix} 6 & -2 \\ -2 & 1 \end{bmatrix} \\
        &= \frac{1}{6 - 4}\begin{bmatrix} 6 & -2 \\ -2 & 1 \end{bmatrix} \\
        &= \frac{1}{2}\begin{bmatrix} 6 & -2 \\ -2 & 1 \end{bmatrix} \\
        &= \boxed{\begin{bmatrix} 3 & -1 \\ -1 & \frac{1}{2} \end{bmatrix}} \\
\end{align}
$$
Solving for $\textbf{A}x = b_1$.
$$
\begin{align}
    \textbf{A}x &= b_1 \\
    x &= \textbf{A}^{-1}b_1 \\
        &= \begin{bmatrix} 3 & -1 \\ -1 & \frac{1}{2} \end{bmatrix}\begin{bmatrix} 3 \\ 5 \end{bmatrix} \\
        &= \begin{bmatrix} (3)(3) + (-1)(5) \\ (-1)(3) + (\frac{1}{2})(5) \end{bmatrix} \\
        &= \begin{bmatrix} 9 - 5 \\ -3 + \frac{5}{2} \end{bmatrix} \\
        &= \boxed{\begin{bmatrix} 4 \\ -\frac{1}{2} \end{bmatrix}} \\
\end{align}
$$
Solving for $\textbf{A}x = b_2$.
$$
\begin{align}
    \textbf{A}x &= b_2 \\
    x &= \textbf{A}^{-1}b_2 \\
        &= \begin{bmatrix} 3 & -1 \\ -1 & \frac{1}{2} \end{bmatrix}\begin{bmatrix} -1 \\ 2 \end{bmatrix} \\
        &= \begin{bmatrix} (3)(-1) + (-1)(2) \\ (-1)(-1) + (\frac{1}{2})(2) \end{bmatrix} \\
        &= \begin{bmatrix} -3 - 2 \\ 1 + 1 \end{bmatrix} \\
        &= \boxed{\begin{bmatrix} -5 \\ 2 \end{bmatrix}} \\
\end{align}
$$
Solving for $\textbf{A}x = b_3$.
$$
\begin{align}
    \textbf{A}x &= b_3 \\
    x &= \textbf{A}^{-1}b_3 \\
        &= \begin{bmatrix} 3 & -1 \\ -1 & \frac{1}{2} \end{bmatrix}\begin{bmatrix} 2 \\ 0 \end{bmatrix} \\
        &= \begin{bmatrix} (3)(2) + (-1)(0) \\ (-1)(2) + (\frac{1}{2})(0) \end{bmatrix} \\
        &= \begin{bmatrix} 6 + 0 \\ -2 + 0 \end{bmatrix} \\
        &= \boxed{\begin{bmatrix} 6 \\ -2 \end{bmatrix}} \\
\end{align}
$$

**Pythonic Solution**

In [14]:
A_inv = np.linalg.inv(A)
x_1 = np.matmul(A_inv, b_1)
x_2 = np.matmul(A_inv, b_2)
x_3 = np.matmul(A_inv, b_3)

print("-- A^(-1) --", A_inv, sep="\n")
print("\n-- Ax = b_1 --", x_1, sep="\n")
print("\n-- Ax = b_2 --", x_2, sep="\n")
print("\n-- Ax = b_3 --", x_3, sep="\n")

-- A^(-1) --
[[ 3.  -1. ]
 [-1.   0.5]]

-- Ax = b_1 --
[[ 4. ]
 [-0.5]]

-- Ax = b_2 --
[[-5.]
 [ 2.]]

-- Ax = b_3 --
[[ 6.]
 [-2.]]


- Solve all three linear systems by row reducing the augmented matrix.
$$
\begin{align}
    \begin{bmatrix} \textbf{A} &\bigm| & b_1 & b_2 & b_3 \end{bmatrix}
\end{align}
$$

**Manual Solution**

$$
\begin{align}
    \begin{bmatrix} \textbf{A} &\bigm| & b_1 & b_2 & b_3 \end{bmatrix} = 
    \begin{bmatrix} 
        1 & 2 &\bigm| & 3 & -1 & 2 \\
        2 & 6 &\bigm| & 5 &  2 & 0 \\
    \end{bmatrix}
\end{align}
$$
Perform row operations to reduce the augmented matrix to its reduced row echelon form.
$
\begin{align}
    \begin{bmatrix} 
        1 & 2 &\bigm| & 3 & -1 & 2 \\
        2 & 6 &\bigm| & 5 &  2 & 0 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - 2\textbf{R}_1}
    \begin{bmatrix} 
        1 & 2 &\bigm| &  3 & -1 & 2 \\
        0 & 2 &\bigm| & -1 &  4 & -4 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix} 
        1 & 2 &\bigm| &  3 & -1 & 2 \\
        0 & 2 &\bigm| & -1 &  4 & -4 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_1 - \textbf{R}_2}
    \begin{bmatrix} 
        1 & 0 &\bigm| &  4 & -5 &  6 \\
        0 & 2 &\bigm| & -1 &  4 & -4 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix} 
        1 & 0 &\bigm| &  4 & -5 &  6 \\
        0 & 2 &\bigm| & -1 &  4 & -4 \\
    \end{bmatrix}
    \xrightarrow{\frac{1}{2}\textbf{R}_2}
    \boxed{\begin{bmatrix} 1 & 0 &\bigm| &  4 & -5 &  6 \\ 0 & 1 &\bigm| & -\frac{1}{2} & 2 & -2 \end{bmatrix}}
\end{align}
$
From the reduced row echelon form, we can then get the answers to the linear equations.
$$
\begin{align}
    \text{For } \textbf{A}x = b_1 \rightarrow \boxed{x = \begin{bmatrix} 4  \\ -\frac{1}{2} \end{bmatrix}} \\
    \text{For } \textbf{A}x = b_2 \rightarrow \boxed{x = \begin{bmatrix} -5 \\ 2 \end{bmatrix}} \\
    \text{For } \textbf{A}x = b_3 \rightarrow \boxed{x = \begin{bmatrix} 6  \\ -2 \end{bmatrix}} \\
\end{align}
$$

**Pythonic Solution**

In [15]:
augmented_matrix = np.hstack((A, b_1, b_2, b_3))

rref, solution = reduced_row_echelon_form(augmented_matrix, augment_size=b_1.shape[1] + b_2.shape[1] + b_3.shape[1])

print("-- Reduced Row Echelon Form --", rref, sep="\n")
print("\n-- Solution --", solution, sep="\n")
print("\n-- Ax = b_1 --", solution[:, :1], sep="\n")
print("\n-- Ax = b_2 --", solution[:, 1:2], sep="\n")
print("\n-- Ax = b_3 --", solution[:, 2:], sep="\n")

-- Reduced Row Echelon Form --
[[ 1.   0.   4.  -5.   6. ]
 [ 0.   1.  -0.5  2.  -2. ]]

-- Solution --
[[ 4.  -5.   6. ]
 [-0.5  2.  -2. ]]

-- Ax = b_1 --
[[ 4. ]
 [-0.5]]

-- Ax = b_2 --
[[-5.]
 [ 2.]]

-- Ax = b_3 --
[[ 6.]
 [-2.]]


**4. In each given, determine $b$ is in $col(\textbf{A})$, and $w$ is in $row(\textbf{A})$**

$$
\begin{align}
    \textbf{A} = \begin{bmatrix} 1 & 0 & -1 \\ 1 & 1 & 1 \end{bmatrix},\
    b = \begin{bmatrix} 3 \\ 2 \end{bmatrix},\
    w = \begin{bmatrix} -1 & 1 & 1 \end{bmatrix}
\end{align}
$$

**Manual Solution**

To determine whether $b$ is in $col(\textbf{A})$, we need to show that $\textbf{A}x = b$ via row operations to form a row echelon or reduced row echelon.
$
\begin{align}
    \begin{bmatrix}
        1 & 0 & -1 &\bigm| & 3 \\
        1 & 1 &  1 &\bigm| & 2 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - \textbf{R}_1}
    \boxed{\begin{bmatrix} 1 & 0 & -1 &\bigm| &  3 \\ 0 & 1 &  2 &\bigm| & -1 \\ \end{bmatrix}}
\end{align}
$
This is now in proper row echelon form, indicating that $\boxed{b \text{ is in } col(\textbf{A})}$.


To determine whether $w$ is in $row(\textbf{A})$, we need to reduce the augmented matrix $\begin{bmatrix} \textbf{A} \\ \hline w \end{bmatrix}$ via row operations to form a row echelon or reduced row echelon.
$
\begin{align}
    \begin{bmatrix}
        1 & 0 & -1 \\
        1 & 1 &  1 \\
        \hline
        -1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 + \textbf{R}_1}
    \begin{bmatrix}
        1 & 0 & -1 \\
        1 & 1 &  1 \\
        \hline
        0 & 1 & 0 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - \textbf{R}_1}
    \begin{bmatrix}
        1 & 0 & -1 \\
        0 & 1 &  2 \\
        \hline
        0 & 1 & 0 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - \textbf{R}_3}
    \begin{bmatrix}
        1 & 0 & -1 \\
        0 & 0 &  2 \\
        \hline
        0 & 1 & 0 \\
    \end{bmatrix}
\end{align}
$
$ 
\begin{align}
    \begin{bmatrix}
        1 & 0 & -1 \\
        0 & 0 &  2 \\
        \hline
        0 & 1 & 0 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 \leftrightarrow \textbf{R}_3}
    \begin{bmatrix}
        1 & 0 & -1 \\
        0 & 1 & 0 \\
        \hline
        0 & 0 &  2 \\
    \end{bmatrix}
    \xrightarrow{\frac{1}{2}\textbf{R}_3}
    \begin{bmatrix}
        1 & 0 & -1 \\
        0 & 1 & 0 \\
        \hline
        0 & 0 &  1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_1 + \textbf{R}_3}
    \boxed{\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ \hline 0 & 0 &  1 \\ \end{bmatrix}}
\end{align}
$
This is now in proper reduced row echelon form, indicating that $\boxed{w \text{ is in } row(\textbf{A})}$.

**Pythonic Solution**

In [16]:
A = np.array([[1, 0, -1], [1, 1, 1]])
b = np.array([[3], [2]])
w = np.array([[-1, 1, 1]])

b_rref, b_sol = reduced_row_echelon_form(np.hstack((A, b)))
w_rref, w_sol = reduced_row_echelon_form(np.vstack((A, w)), augment_size=0)

print("-- Ax = b RREF --", b_rref, sep="\n")
print("b is in col(A)?", "Yes." if b_sol is not None else "No.")

print("\n-- Ax = w RREF --", w_rref, sep="\n")
print("w is in row(A)?", "Yes." if w_sol is not None else "No.")

-- Ax = b RREF --
[[ 1.  0. -1.  3.]
 [ 0.  1.  2. -1.]]
b is in col(A)? Yes.

-- Ax = w RREF --
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
w is in row(A)? Yes.


$$
\begin{align}
    \textbf{A} = \begin{bmatrix} 1 & 1 & -1 \\ 1 & 3 & 0 \\ 3 & -1 & -5 \end{bmatrix},\
    b = \begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix},\
    w = \begin{bmatrix} 1 & -3 & -3 \end{bmatrix}
\end{align}
$$

**Manual Solution**

To determine whether $b$ is in $col(\textbf{A})$, we need to show that $\textbf{A}x = b$ via row operations to form a row echelon or reduced row echelon.
$
\begin{align}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        1 & 3 & 0 &\bigm| & 2 \\
        3 & -1 & -5 &\bigm| & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - \textbf{R}_1}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        0 & 2 & 1 &\bigm| & 1 \\
        3 & -1 & -5 &\bigm| & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 - 3\textbf{R}_1}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        0 & 2 & 1 &\bigm| & 1 \\
        0 & -4 & -2 &\bigm| & -2 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        0 & 2 & 1 &\bigm| & 1 \\
        0 & -4 & -2 &\bigm| & -2 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 + 2\textbf{R}_2}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        0 & 2 & 1 &\bigm| & 1 \\
        0 & 0 & 0 &\bigm| & 0 \\
    \end{bmatrix}
    \xrightarrow{\frac{1}{2}\textbf{R}_2}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        0 & 1 & \frac{1}{2} &\bigm| & \frac{1}{2} \\
        0 & 0 & 0 &\bigm| & 0 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 1 & -1 &\bigm| & 1 \\
        0 & 1 & \frac{1}{2} &\bigm| & \frac{1}{2} \\
        0 & 0 & 0 &\bigm| & 0 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_1 - \textbf{R}_2}
    \boxed{\begin{bmatrix}
        1 & 0 & -\frac{3}{2} &\bigm| & \frac{1}{2} \\
        0 & 1 & \frac{1}{2} &\bigm| & \frac{1}{2} \\
        0 & 0 & 0 &\bigm| & 0 \\
    \end{bmatrix}}
\end{align}
$
This is now in proper row echelon form, indicating that $\boxed{b \text{ is in } col(\textbf{A})}$.

To determine whether $w$ is in $row(\textbf{A})$, we need to reduce the augmented matrix $\begin{bmatrix} \textbf{A} \\ \hline w \end{bmatrix}$  via row operations to form a row echelon or reduced row echelon.
$
\begin{align}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        1 & 3 & 0 \\ 
        3 & -1 & -5 \\
        \hline
        1 & -3 & -3 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - \textbf{R}_1}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        3 & -1 & -5 \\
        \hline
        1 & -3 & -3 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 - 3\textbf{R}_1}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        0 & -4 & -2 \\
        \hline
        1 & -3 & -3 \\ 
    \end{bmatrix}
\end{align}
$
$ 
\begin{align} 
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        0 & -4 & -2 \\
        \hline
        1 & -3 & -3 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_4 - \textbf{R}_1}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        0 & -4 & -2 \\
        \hline
        0 & -4 & -2 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_4 + 2\textbf{R}_2}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        0 & -4 & -2 \\
        \hline
        0 & 0 & 0 \\ 
    \end{bmatrix}
\end{align}
$
$ 
\begin{align}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        0 & -4 & -2 \\
        \hline
        0 & 0 & 0 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 + 2\textbf{R}_2}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 2 & 1 \\ 
        0 & 0 & 0 \\
        \hline
        0 & 0 & 0 \\ 
    \end{bmatrix}
    \xrightarrow{\frac{1}{2}\textbf{R}_2}
    \begin{bmatrix} 
        1 & 1 & -1 \\ 
        0 & 1 & \frac{1}{2} \\ 
        0 & 0 & 0 \\
        \hline
        0 & 0 & 0 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_1 - \textbf{R}_2}
    \boxed{\begin{bmatrix} 
        1 & 0 & -\frac{3}{2} \\ 
        0 & 1 & \frac{1}{2} \\ 
        0 & 0 & 0 \\
        \hline
        0 & 0 & 0 \\ 
    \end{bmatrix}}
\end{align}
$
This is now in proper row echelon form, indicating that $\boxed{w \text{ is in } row(\textbf{A})}$.

**Pythonic Solution**

In [17]:
A = np.array([[1, 1, -1], [1, 3, 0], [3, -1, -5]])
b = np.array([[1], [2], [1]])
w = np.array([[1, -3, -3]])

b_rref, b_sol = reduced_row_echelon_form(np.hstack((A, b)))
w_rref, w_sol = reduced_row_echelon_form(np.vstack((A, w)), augment_size=0)

print("-- Ax = b RREF --", b_rref, sep="\n")
print("b is in col(A)?", "Yes." if b_sol is not None else "No.")

print("\n-- Ax = w RREF --", w_rref, sep="\n")
print("w is in row(A)?", "Yes." if w_sol is not None else "No.")

-- Ax = b RREF --
[[ 1.   0.  -1.5  0.5]
 [ 0.   1.   0.5  0.5]
 [ 0.   0.   0.   0. ]]
b is in col(A)? Yes.

-- Ax = w RREF --
[[ 1.   0.  -1.5]
 [ 0.   1.   0.5]
 [ 0.   0.   0. ]
 [ 0.   0.   0. ]]
w is in row(A)? Yes.


**5. Find the rank and nullity of**

$$
\begin{align}
    \textbf{A} = \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\ 
        6 & 3 & 5 & 1 & 0 \\ 
        1 & 0 & 2 & 2 & 5 \\ 
        1 & 1 & 1 & 1 & 1 \\ 
    \end{bmatrix}
\end{align}
$$

To get the $rank(\textbf{A})$ and $nullity(\textbf{A})$, we must first transform the matrix into a row echelon form or reduced echelon form.
$
\begin{align}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\ 
        6 & 3 & 5 & 1 & 0 \\ 
        1 & 0 & 2 & 2 & 5 \\ 
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - 6\textbf{R}_4}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\ 
        0 & -3 & -1 & -5 & -6 \\ 
        1 & 0 & 2 & 2 & 5 \\ 
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_3 - \textbf{R}_4}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\ 
        0 & -3 & -1 & -5 & -6 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        2 & 4 & 0 & 0 & 1 \\ 
        0 & -3 & -1 & -5 & -6 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_1 - 2\textbf{R}_4}
    \begin{bmatrix}
        0 & 2 & -2 & -2 & -1 \\ 
        0 & -3 & -1 & -5 & -6 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        1 & 1 & 1 & 1 & 1 \\
    \end{bmatrix}
    \xrightarrow{\textbf{R}_1 \leftrightarrow \textbf{R}_4}
    \begin{bmatrix}
        1 & 1 & 1 & 1 & 1 \\
        0 & -3 & -1 & -5 & -6 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        0 & 2 & -2 & -2 & -1 \\ 
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 1 & 1 & 1 \\
        0 & -3 & -1 & -5 & -6 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        0 & 2 & -2 & -2 & -1 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_4 + 2\textbf{R}_3}
    \begin{bmatrix}
        1 & 1 & 1 & 1 & 1 \\
        0 & -3 & -1 & -5 & -6 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        0 & 0 & 0 & 0 & 7 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 - 3\textbf{R}_3}
    \begin{bmatrix}
        1 & 1 & 1 & 1 & 1 \\
        0 &  0 & -4 & -8 & -18 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        0 & 0 & 0 & 0 & 7 \\ 
    \end{bmatrix}
\end{align}
$
$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 1 & 1 & 1 \\
        0 &  0 & -4 & -8 & -18 \\ 
        0 & -1 & 1 & 1 & 4 \\ 
        0 & 0 & 0 & 0 & 7 \\ 
    \end{bmatrix}
    \xrightarrow{\textbf{R}_2 \leftrightarrow \textbf{R}_3}
    \begin{bmatrix}
        1 & 1 & 1 & 1 & 1 \\
        0 & -1 & 1 & 1 & 4 \\ 
        0 &  0 & -4 & -8 & -18 \\ 
        0 & 0 & 0 & 0 & 7 \\ 
    \end{bmatrix}
\end{align}
$
Now, that we have the matrix in its row echelon form, counting the number of non-zero rows, gives us the rank of the matrix, in this case $rank(\textbf{A}) = 4$.

For nullity, we can derive it using the formula $rank(\textbf{A})+ nullity(\textbf{A}) = n$, where $n$ is the number of columns of $\textbf{A}$. By simple transposition, we have $nullity(\textbf{A}) = n - rank(\textbf{A}) = 5 - 4 = 1$.

$\boxed{\therefore \text{The given matrix has a }rank(\textbf{A}) = 4\text{ and }nullity(\textbf{A}) = 1}$.