# Systems of Linear Equation Homework Answers
**=======================**
#### Name: Sherly R. Jao
#### BSCS - 3 | CS 3101N

#### Assignment 1
1. create a function that will automate backward substitution to complete the given python functions that will automate forward elimination to determine the solution

**Given Code**

In [371]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination

def RowSwap(A,k,l):
    # =============================================================================
    #     A is a NumPy array.  RowSwap will return duplicate array with rows
    #     k and l swapped.
    # =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
    # =============================================================================
    #     A is a NumPy array.  RowScale will return duplicate array with the
    #     entries of row k multiplied by scale.
    # =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
    # =============================================================================
    #     A is a numpy array.  RowAdd will return duplicate array with row
    #     l modifed.  The new values will be the old values of row l added to
    #     the values of row k, multiplied by scale.
    # =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

**Python Code for automate backward substitution**

In [372]:
#  Python code function for backward substitution
def get_backward_substitution(A):
    n = A.shape[0]
    x =np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = A[i, -1] / A[i, i]

        for j in range(i - 1, -1, -1):
            A[j, -1] -= A[j, i] * x[i]
            A[j, i] = 0

    return x

**Testing for python code**

- Given the following equations:

$$
\begin{align}
    x_1 - x_2 + x_3 &= 3 \\
    x_2 + 2x_3 &= 4 \\
    x_3 &= 2
\end{align}
$$

- The result of our function code should be the following solution:

$$
\begin{align}
    \therefore x_1 = 1, x_2 = 0, x_3 = 2
\end{align}
$$

In [373]:
import numpy as np

def RowSwap(A,k,l):
    # =============================================================================
    #     A is a NumPy array.  RowSwap will return duplicate array with rows
    #     k and l swapped.
    # =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
    # =============================================================================
    #     A is a NumPy array.  RowScale will return duplicate array with the
    #     entries of row k multiplied by scale.
    # =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
    # =============================================================================
    #     A is a numpy array.  RowAdd will return duplicate array with row
    #     l modifed.  The new values will be the old values of row l added to
    #     the values of row k, multiplied by scale.
    # =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

#  Python code function for backward substitution
def get_backward_substitution(A):
    n = A.shape[0]
    x =np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = A[i, -1] / A[i, i]

        for j in range(i - 1, -1, -1):
            A[j, -1] -= A[j, i] * x[i]
            A[j, i] = 0

    return x

A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])

## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print("A1")
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print("A2")
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print("A3")
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print("A4")
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print("A5")
print(A5,'\n')

solution = get_backward_substitution(A5)
print("> Solution")
for i in range(len(solution)):
    print(f"x_{i + 1} = {solution[i]}")

A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

> Solution
x_1 = 1.0
x_2 = 0.0
x_3 = 2.0


#### Assigment 2

1. Provide reason why each o the following equations is, or is not, a linear equation

*1.a.*
$$
\begin{align}
    cos\theta x + 4y + z = \sqrt{3} \\
\end{align}
$$

- By definition, a linear equation follows the form: $ax_1 + bx_2 + cx_3 = d$ where $a, b, c,$ and $d$ are constants, in our given equation, the coefficient of the first expression, $cos\theta$ is not a constant. $\therefore$ this equation is **NOT a linear equation**

*1.b.*
$$
\begin{align}
    cos\theta x4y + z = \sqrt{3} \\
\end{align}
$$

- By definition, a linear equation follows the form: $ax_1 + bx_2 + cx_3 = d$ where $a, b, c,$ and $d$ are constants, in our given equation, the coefficient of the first expression, $cos\theta x4$ is not a constant. $\therefore$ this equation is **NOT a linear equation**

*1.c.*
$$
\begin{align}
    x^{-1} + 7y + z = \sin(\frac{\pi}{2}) \\
\end{align}
$$

- By definition, a linear equation follows the form: $ax_1 + bx_2 + cx_3 = d$ where $a, b, c,$ and $d$ are constants, in our given equation, the variables are not all raised to a degree of one. $\therefore$ this equation is **NOT a linear equation**

*1.d.*
$$
\begin{align}
    x^1 + y^1 + z^1 = 0 \\
\end{align}
$$

- By definition, a linear equation follows the form: $ax_1 + bx_2 + cx_3 = d$ where $a, b, c,$ and $d$ are constants, it can be seen that out given equaltion follows this form. $\therefore$ this equation is **a linear equation**

2. Find the solutions to the linear equations:

*2.a*
$$
\begin{align}
    2x_1 + 3x_2 = 5 \\
\end{align}
$$

- We need to transform the linear equation into an augmented matrix, so let:
$$
\begin{align}
    x_2 &= s
\end{align}
$$
- the new equation becomes: $2x_1 + 3s = 5$. Solving for $x_1 = \frac{5 - 3s}{2}$. The augmented matrix is of the form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & | & \frac{5 - 3s}{2} \\
        0 & 1 & | & s
    \end{bmatrix}
\end{align}
$$
- We can have any arbitrary values of $s$ that will satisfy $\frac{5 - 3s}{2}$, these arbitrary values are the solution to $x_2$. While the result from the formula $\frac{5 - 3s}{2}$ is the solution to $x_1$.

*2.b*
$$
\begin{align}
    4x_1 + 3x_2 + 2x_3 = 1 \\
\end{align}
$$

- We need to transform the linear equation into an augmented matrix, so let:
$$
\begin{align}
    x_2 &= s \\
    x_3 &= t
\end{align}
$$
- the new equation becomes: $4x_1 + 3s + 2t = 1$. Solving for $x_1 = \frac{1 - 3s - 2t}{4}$. The augmented matrix is of the form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{1 - 3s - 2t}{4} \\
        0 & 1 & 0 & | & s \\
        0 & 0 & 1 & | & t
    \end{bmatrix}
\end{align}
$$
- We can have any arbitrary values of $s$ and $t$ that will satisfy $\frac{1 - 3s - 2t}{4}$, these arbitrary values are the solution to $x_2$ and $x_3$ While the result from the formula $\frac{1 - 3s - 2t}{4}$ is the solution to $x_1$.

*2.c*
$$
\begin{align}
    3x - 6y = 0 \\
\end{align}
$$

- We need to transform the linear equation into an augmented matrix, so let:
$$
\begin{align}
    y &= s \\
\end{align}
$$
- the new equation becomes: $3x - 6s = 0$. Solving for $x = 2s$. The augmented matrix is of the form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & 0 & | & 2s \\
        0 & 1 & 0 & | & s
    \end{bmatrix}
\end{align}
$$
- We can have any arbitrary values of $s$ that will satisfy $2s$, these arbitrary values are the solution to $y$. While the result from the formula $2s$ is the solution to $x$.

3. Solve the following systems of linear equations
- We first transform the linear equations into an augmented matrix, then reduce it to its reduced row echelon form to determine its solution. Then we will be using a simple python code to check the solutions.

*3.a.*
$$
\begin{align}
    x - y &= 0 \\
    2x + y &= 3
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & -1 & | & 0 \\
        2 & 1 & | & 3
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & -1 & | & 0 \\
        2 & 1 & | & 3
    \end{bmatrix}
    \xrightarrow{R_2 - 2R_1}
    \begin{bmatrix}
        1 & -1 & | & 0 \\
        0 & 3 & | & 3
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & -1 & | & 0 \\
        0 & 3 & | & 3
    \end{bmatrix}
    \xrightarrow{\frac{R_2}{3}}
    \begin{bmatrix}
        1 & -1 & | & 0 \\
        0 & 1 & | & 1
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & -1 & | & 0 \\
        0 & 1 & | & 1
    \end{bmatrix}
    \xrightarrow{R_1 + R_2}
    \begin{bmatrix}
        1 & 0 & | & 1 \\
        0 & 1 & | & 1
    \end{bmatrix}
\end{align}
$$

- $\therefore$ the solution of the following equations are $x = 1$ and $y = 1$

**Pythonic Solution**

In [374]:
import numpy as np

# Coefficient matrix
A = np.array([[1, -1], [2, 1]])

# Right-hand side column vector
B = np.array([0, 3])

solution = np.linalg.solve(A, B)
print("> Solution")
print(f"x = {solution[0]}", f"\ny = {solution[1]}")

> Solution
x = 1.0 
y = 1.0


*3.b.*
$$
\begin{align}
    x + 5y &= -1 \\
    -x + y &= -5 \\
    2x + 4y &= 4
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        -1 & 1 & | & -5 \\
        2 & 4 & | & 4
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        -1 & 1 & | & -5 \\
        2 & 4 & | & 4
    \end{bmatrix}
    \xrightarrow{R_2 + R_1}
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        0 & 6 & | & -6 \\
        2 & 4 & | & 4
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        0 & 6 & | & -6 \\
        2 & 4 & | & 4
    \end{bmatrix}
    \xrightarrow{R_3 - 2R_1}
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        0 & 6 & | & -6 \\
        0 & -6 & | & 6
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        0 & 6 & | & -6 \\
        0 & -6 & | & 6
    \end{bmatrix}
    \xrightarrow{\frac{R_2}{6}}
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        0 & 1 & | & -1 \\
        0 & -6 & | & 6
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 5 & | & -1 \\
        0 & 1 & | & -1 \\
        0 & -6 & | & 6
    \end{bmatrix}
    \xrightarrow{R_1 - 5R_2}
    \begin{bmatrix}
        1 & 0 & | & 4 \\
        0 & 1 & | & -1 \\
        0 & -6 & | & 6
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & | & 4 \\
        0 & 1 & | & -1 \\
        0 & -6 & | & 6
    \end{bmatrix}
    \xrightarrow{R_3 + 6R_2}
    \begin{bmatrix}
        1 & 0 & | & 4 \\
        0 & 1 & | & -1 \\
        0 & 0 & | & 0
    \end{bmatrix} \\
\end{align}
$$

- $\therefore$ the solution of the following equations are $x = 4$ and $y = -1$

**Pythonic Solution**

In [375]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 5],
              [-1, 1],
              [2, 4]])

# Right-hand side column vector
B = np.array([-1, -5, 4])

solution = np.linalg.lstsq(A, B, rcond=None)[0]
print("Solution:")
print(solution)

Solution:
[ 4. -1.]


*3.c.*
$$
\begin{align}
    2x_1 + 3x_2 - x_3 &= -1 \\
    x_1 + x_3 &= 0 \\
    -x_1 +2x_2 - 2x_3 &= 0
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        2 & 3 & -1 & | & -1 \\
        1 & 0 & 1 & | & 0 \\
        -1 & 2 & -2 & | & 0
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        2 & 3 & -1 & | & -1 \\
        1 & 0 & 1 & | & 0 \\
        -1 & 2 & -2 & | & 0
    \end{bmatrix}
    \xrightarrow{\frac{R_1}{2}}
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        1 & 0 & 1 & | & 0 \\
        -1 & 2 & -2 & | & 0
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        1 & 0 & 1 & | & 0 \\
        -1 & 2 & -2 & | & 0
    \end{bmatrix}
    \xrightarrow{R_2 - R_1}
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        0 & -\frac{3}{2} & \frac{3}{2} & | & \frac{1}{2} \\
        -1 & 2 & -2 & | & 0
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        0 & -\frac{3}{2} & \frac{3}{2} & | & \frac{1}{2} \\
        -1 & 2 & -2 & | & 0
    \end{bmatrix}
    \xrightarrow{R_3 + R_1}
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        0 & -\frac{3}{2} & \frac{3}{2} & | & \frac{1}{2} \\
        0 & \frac{7}{2} & -\frac{5}{2} & | & -\frac{1}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        0 & -\frac{3}{2} & \frac{3}{2} & | & \frac{1}{2} \\
        0 & \frac{7}{2} & -\frac{5}{2} & | & -\frac{1}{2}
    \end{bmatrix}
    \xrightarrow{- \frac{2R_2}{3}}
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & \frac{7}{2} & -\frac{5}{2} & | & -\frac{1}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & \frac{3}{2} & -\frac{1}{2} & | & -\frac{1}{2} \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & \frac{7}{2} & -\frac{5}{2} & | & -\frac{1}{2}
    \end{bmatrix}
    \xrightarrow{R_1 - \frac{3R_2}{2}}
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & \frac{7}{2} & -\frac{5}{2} & | & -\frac{1}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & \frac{7}{2} & -\frac{5}{2} & | & -\frac{1}{2}
    \end{bmatrix}
    \xrightarrow{R_3 - \frac{7R_2}{2}}
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & 0 & 1 & | & \frac{2}{3}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & 0 & 1 & | & \frac{2}{3}
    \end{bmatrix}
    \xrightarrow{R_1 - R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & - \frac{2}{3} \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & 0 & 1 & | & \frac{2}{3}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 0 & | & - \frac{2}{3} \\
        0 & 1 & -1 & | & - \frac{1}{3} \\
        0 & 0 & 1 & | & \frac{2}{3}
    \end{bmatrix}
    \xrightarrow{R_2 +  R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & -\frac{2}{3} \\
        0 & 1 & 0 & | & \frac{1}{3} \\
        0 & 0 & 1 & | & \frac{2}{3}
    \end{bmatrix}
\end{align}
$$

- $\therefore$ the solution of the following equations are $x_1 = -\frac{2}{3}$, $yx_2 = \frac{1}{3}$ and $x_3 = \frac{2}{3}$

**Pythonic Solution**

In [376]:
import numpy as np

# Coefficient matrix
A = np.array([[2, 3, -1], [1, 0, 1], [-1, 2, -2]])

# Right-hand side column vector
B = np.array([-1, 0, 0])

solution = np.linalg.solve(A, B)
print("> Solution")
print(f"x_1 = {solution[0]:.2f}", f"\nx_2 = {solution[1]:.2f}", f"\nx_3 = {solution[2]:.2f}")

> Solution
x_1 = -0.67 
x_2 = 0.33 
x_3 = 0.67


4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or neither both.

*4.a*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & 1 \\
        0 & 0 & 3 \\
        0 & 1 & 0
    \end{bmatrix}
\end{align}
$$
- In the first row, the left-most nonzero entry is 1, and the column containing it has all other entries equal to 0, but there is no leading 1 in the second row. For a matrix to be in row echelon form, each subsequent row should have a leading 1 to the right of the previous row. $\therefore$ the given matrix is **NEITHER in row echelon form nor reduced row echelon form**

*4.b*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        7 & 0 & 1 & 0 \\
        0 & 1 & -1 & 4 \\
        0 & 0 & 0 & 0
    \end{bmatrix}
\end{align}
$$
- This matrix satisfies the conditions of being in its row echelon form since, the leading non-zero in the second row is in the right of the leading non-zero of the first row and the majority of the row with zeroes are located in the lowest row. But in the first row, the left-most nonzero entry is 7, which violates the condition for reduced row echelon form. $\therefore$ the given matrix is **in row echelon form BUT NOT in reduced row echelon form**

*4.c*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        0 & 1 & 3 & 0 \\
        0 & 0 & 0 & 1
    \end{bmatrix}
\end{align}
$$
- This matrix satisfies the conditions of being in its row echelon form since, the majority of the row with zeroes are located in the lowest row. But the leading entry of the first row is not one, which violates the condition for reduced row echelon form. $\therefore$ the given matrix is **in row echelon form BUT NOT in reduced row echelon form**

*4.d*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        0 & 0 & 0 \\
        0 & 0 & 0 \\
        0 & 0 & 0
    \end{bmatrix}
\end{align}
$$
- This matrix consists entirely of zeros.In these forms, the primary conditions are satisfied, including the fact that all zero rows, if any, are at the bottom. $\therefore$ the given matrix is **BOTH in row echelon form and in reduced row echelon form**

*4.e*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & 3 & -4 & 0 \\
        0 & 0 & 0 & 0 & 0 \\
        0 & 1 & 5 & 0 & 1
    \end{bmatrix}
\end{align}
$$
- In this matrix, the majority of the row with zeroes is not in the lowest row, which violates the condition for the row echelon form. $\therefore$ the given matrix is **NEITHER in row echelon form nor reduced row echelon form**

*4.f*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        0 & 0 & 1 \\
        0 & 1 & 0 \\
        1 & 0 & 0
    \end{bmatrix}
\end{align}
$$
- This matrix violates the condition of being a row echelon form, since the leading nonzero entry of the second row is on the left of the leading nonzero entry of the first row. $\therefore$ the given matrix is **NEITHER in row echelon form nor reduced row echelon form**

*4.g*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 2 & 3 \\
        1 & 0 & 0 \\
        0 & 1 & 1 \\
        0 & 0 & 1
    \end{bmatrix}
\end{align}
$$
- This matrix violates the condition of being a row echelon form, since the leading nonzero entry of the second row is not on the right of the leading nonzero entry of the first row. $\therefore$ the given matrix is **NEITHER in row echelon form nor reduced row echelon form**

*4.h*
- Let's analyze the matrix:
$$
\begin{align}
    \begin{bmatrix}
        2 & 1 & 3 & 5 \\
        0 & 0 & 1 & -1 \\
        0 & 0 & 0 & 3 \\
        0 & 0 & 0 & 0 \\
    \end{bmatrix}
\end{align}
$$
- The leading nonzero entry are all in the right of the row above them and the majority of the row with zeroes is not in the lowest row, which satisfies teh condition of being a row echelon form, but the leading entry of the first row is 2 which violates the condition of being a reduce row echelon form $\therefore$ the given matrix is **in row echelon form BUT NOT in reduced row echelon form**

5. Solve the following systems of linear equations
- We first transform the linear equations into an augmented matrix, then reduce it to its reduced row echelon form to determine its solution. Then we will be using a simple python code to check the solutions.

*5.a.*
$$
\begin{align}
    x_1 + 2x_2 - 3x_3 = 9 \\
    2x_1 - x_2 -x_3 = 0 \\
    4x_1 - x_2 + x_3 = 4
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        2 & -1 & -1 & | & 0 \\
        4 & -1 & 1 & | & 4
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        2 & -1 & -1 & | & 0 \\
        4 & -1 & 1 & | & 4
    \end{bmatrix}
    \xrightarrow{R_2 - 2R_1}
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        0 & -5 & 5 & | & 18 \\
        4 & -1 & 1 & | & 4
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        0 & -5 & 5 & | & 18 \\
        4 & -1 & 1 & | & 4
    \end{bmatrix}
    \xrightarrow{R_3 - 4R_1}
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        0 & -5 & 5 & | & 18 \\
        0 & -9 & 13 & | & -32
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        0 & -5 & 5 & | & 18 \\
        0 & -9 & 13 & | & -32
    \end{bmatrix}
    \xrightarrow{- \frac{R_2}{5}}
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & -9 & 13 & | & -32
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 2 & -3 & | & 9 \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & -9 & 13 & | & -32
    \end{bmatrix}
    \xrightarrow{R_1 - 2R_2}
    \begin{bmatrix}
        1 & 0 & -1 & | & \frac{9}{5} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & -9 & 13 & | & -32
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & \frac{9}{5} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & -9 & 13 & | & -32
    \end{bmatrix}
    \xrightarrow{R_3 + 9R_2}
    \begin{bmatrix}
        1 & 0 & -1 & | & \frac{9}{5} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & 0 & 4 & | & \frac{2}{5}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & \frac{9}{5} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & 0 & 4 & | & \frac{2}{5}
    \end{bmatrix}
    \xrightarrow{\frac{R_3}{4}}
    \begin{bmatrix}
        1 & 0 & -1 & | & \frac{9}{5} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & 0 & 1 & | & \frac{1}{10}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & \frac{9}{5} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & 0 & 1 & | & \frac{1}{10}
    \end{bmatrix}
    \xrightarrow{R_1 + R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{19}{10} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & 0 & 1 & | & \frac{1}{10}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{19}{10} \\
        0 & 1 & -1 & | & \frac{18}{5} \\
        0 & 0 & 1 & | & \frac{1}{10}
    \end{bmatrix}
    \xrightarrow{R_2 + R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{19}{10} \\
        0 & 1 & 0 & | & \frac{37}{10} \\
        0 & 0 & 1 & | & \frac{1}{10}
    \end{bmatrix}
\end{align}
$$

- $\therefore$ the solution of the following equations are $x_1 = \frac{19}{10}$, $x_2 = \frac{37}{10}$ and $x_3 = \frac{1}{10}$

**Pythonic Solution**

In [377]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 2, -3], [2, -1, -1], [4, -1, 1]])

# Right-hand side column vector
B = np.array([9, 0, 4])

solution = np.linalg.solve(A, B)
print("> Solution")
print(f"x_1 = {solution[0]:.2f}", f"\nx_2 = {solution[1]:.2f}", f"\nx_3 = {solution[2]:.2f}")

> Solution
x_1 = 1.90 
x_2 = 3.70 
x_3 = 0.10


*5.b.*
$$
\begin{align}
    x + 2y = -1 \\
    2x + y + z = 1 \\
    -x + y - z = -1
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        2 & 1 & 1 & | & 1 \\
        -1 & 1 & -1 & | & -1
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        2 & 1 & 1 & | & 1 \\
        -1 & 1 & -1 & | & -1
    \end{bmatrix}
    \xrightarrow{R_2 - 2R_1}
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        0 & -3 & 1 & | & 3 \\
        -1 & 1 & -1 & | & -1
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        0 & -3 & 1 & | & 3 \\
        -1 & 1 & -1 & | & -1
    \end{bmatrix}
    \xrightarrow{R_3 + R_1}
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        0 & -3 & 1 & | & 3 \\
        0 & 3 & -1 & | & -2
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        0 & -3 & 1 & | & 3 \\
        0 & 3 & -1 & | & -2
    \end{bmatrix}
    \xrightarrow{- \frac{R_2}{3}}
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        0 & 1 & -\frac{1}{3} & | & -1 \\
        0 & 3 & -1 & | & -2
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 2 & 0 & | & -1 \\
        0 & 1 & -\frac{1}{3} & | & -1 \\
        0 & 3 & -1 & | & -2
    \end{bmatrix}
    \xrightarrow{R_1 - 2R_2}
    \begin{bmatrix}
        1 & 0 & \frac{2}{3} & | & 1 \\
        0 & 1 & -\frac{1}{3} & | & -1 \\
        0 & 3 & -1 & | & -2
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & \frac{2}{3} & | & 1 \\
        0 & 1 & -\frac{1}{3} & | & -1 \\
        0 & 3 & -1 & | & -2
    \end{bmatrix}
    \xrightarrow{R_3 - 3R_2}
    \begin{bmatrix}
        1 & 0 & \frac{2}{3} & | & 1 \\
        0 & 1 & -\frac{1}{3} & | & -1 \\
        0 & 0 & 0 & | & 1
    \end{bmatrix}
\end{align}
$$

- There is inconsistencies in the last row since $0x + 0y + 0z = 1$ is not possible. $\therefore$ there are **no solutions**

**Pythonic Solution**

In [378]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 2, 0], [2, 1, 1], [-1, 1, -1]])

# Right-hand side column vector
B = np.array([-1, 1, -1])

print("> Solution")
try:
    solution = np.linalg.solve(A, B)
    print(f"x = {solution[0]:.2f}", f"\ny = {solution[1]:.2f}", f"\nz = {solution[2]:.2f}")
except np.linalg.LinAlgError:
    print("No solution exists for the given system of equations.")


> Solution
No solution exists for the given system of equations.


*5.c.*
$$
\begin{align}
    x_1 - 3x_2 - 2x_3 = 0 \\
    -x_1 + 2x_2 + x_3 = 0 \\
    2x_1 + 4x_2 + 6x_3 = 0
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        -1 & 2 & 1 & | & 0 \\
        2 & 4 & 6 & | & 0
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        -1 & 2 & 1 & | & 0 \\
        2 & 4 & 6 & | & 0
    \end{bmatrix}
    \xrightarrow{R_2 + R_1}
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        0 & -1 & -1 & | & 0 \\
        2 & 4 & 6 & | & 0
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        0 & -1 & -1 & | & 0 \\
        2 & 4 & 6 & | & 0
    \end{bmatrix}
    \xrightarrow{R_3 - 2R_1}
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        0 & -1 & -1 & | & 0 \\
        0 & 10 & 10 & | & 0
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        0 & -1 & -1 & | & 0 \\
        0 & 10 & 10 & | & 0
    \end{bmatrix}
    \xrightarrow{-R_2}
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        0 & 1 & 1 & | & 0 \\
        0 & 10 & 10 & | & 0
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & -3 & -2 & | & 0 \\
        0 & 1 & 1 & | & 0 \\
        0 & 10 & 10 & | & 0
    \end{bmatrix}
    \xrightarrow{R_1 + 3R_2}
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & 1 & | & 0 \\
        0 & 10 & 10 & | & 0
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & 1 & | & 0 \\
        0 & 10 & 10 & | & 0
    \end{bmatrix}
    \xrightarrow{R_3 - 10R_2}
    \begin{bmatrix}
        1 & 0 & 1 & | & 0 \\
        0 & 1 & 1 & | & 0 \\
        0 & 0 & 0 & | & 0
    \end{bmatrix}
\end{align}
$$

- If we look at the last row, we can see that the third equation is $0 = 0$, meaning the equation will always be satisfied regardless of the value of $x_1, x_2$ and $x_3$. $\therefore$ there are **infinitely many solutions** to the systems.

**Pythonic Solution**

In [379]:
import numpy as np

# Coefficient matrix
A = np.array([[1, -3, -2], [-1, 2, 1], [2, 4, 6]])

# Right-hand side column vector
B = np.array([0, 0, 0])

solution, _, _, _ = np.linalg.lstsq(A, B, rcond=None)
print("> Solution")
print(solution)

> Solution
[0. 0. 0.]


*5.d.*
$$
\begin{align}
    w + x + 2y + z = 1 \\
    w - x - y + z = 0 \\
    x + y = 1 \\
    w + x + z = 2
\end{align}
$$

**Manual Solution**
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        1 & -1 & -1 & 1 & | & 0 \\
        0 & 1 & 1 & 0 & | & 1 \\
        1 & 1 & 0 & 1 & | & 2 \\
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        1 & -1 & -1 & 1 & | & 0 \\
        0 & 1 & 1 & 0 & | & 1 \\
        1 & 1 & 0 & 1 & | & 2 \\
    \end{bmatrix}
    \xrightarrow{R_2 - R_1}
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        0 & -2 & -3 & 0 & | & -1 \\
        0 & 1 & 1 & 0 & | & 1 \\
        1 & 1 & 0 & 1 & | & 2 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        0 & -2 & -3 & 0 & | & -1 \\
        0 & 1 & 1 & 0 & | & 1 \\
        1 & 1 & 0 & 1 & | & 2 \\
    \end{bmatrix}
    \xrightarrow{R_4 - R_1}
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        0 & -2 & -3 & 0 & | & -1 \\
        0 & 1 & 1 & 0 & | & 1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        0 & -2 & -3 & 0 & | & -1 \\
        0 & 1 & 1 & 0 & | & 1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{-\frac{R_2}{2}}
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 1 & 1 & 0 & | & 1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & 2 & 1 & | & 1 \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 1 & 1 & 0 & | & 1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{R_1 - R_2}
    \begin{bmatrix}
        1 & 0 & \frac{1}{2} & 1 & | & \frac{1}{2} \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 1 & 1 & 0 & | & 1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & \frac{1}{2} & 1 & | & \frac{1}{2} \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 1 & 1 & 0 & | & 1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{R_3 - R_2}
    \begin{bmatrix}
        1 & 0 & \frac{1}{2} & 1 & | & \frac{1}{2} \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & -\frac{1}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & \frac{1}{2} & 1 & | & \frac{1}{2} \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & -\frac{1}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{-2R_3}
    \begin{bmatrix}
        1 & 0 & \frac{1}{2} & 1 & | & \frac{1}{2} \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & \frac{1}{2} & 1 & | & \frac{1}{2} \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{R_1 - \frac{R_3}{2}}
    \begin{bmatrix}
        1 & 0 & 0 & 1 & | & 1 \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 0 & 1 & | & 1 \\
        0 & 1 & \frac{3}{2} & 0 & | & \frac{1}{2} \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{R_2 - \frac{3R_3}{2}}
    \begin{bmatrix}
        1 & 0 & 0 & 1 & | & 1 \\
        0 & 1 & 0 & 0 & | & 2 \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 0 & 1 & | & 1 \\
        0 & 1 & 0 & 0 & | & 2 \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & -2 & 0 & | & 1 \\
    \end{bmatrix}
    \xrightarrow{R_4 + 2R_3}
    \begin{bmatrix}
        1 & 0 & 0 & 1 & | & 1 \\
        0 & 1 & 0 & 0 & | & 2 \\
        0 & 0 & 1 & 0 & | & -1 \\
        0 & 0 & 0 & 0 & | & -1 \\
    \end{bmatrix}
\end{align}
$$

- There is inconsistencies in the last row since $0w + 0x + 0y + 0z = -1$ is not possible. $\therefore$ there are **no solutions**

**Pythonic Solution**

In [380]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 1, 2, 1], [1, -1, -1, 1], [0, 1, 1, 0], [1, 1, 0, 1]])

# Right-hand side column vector
B = np.array([1, 0, 1, 2])

print("> Solution")
try:
    solution = np.linalg.solve(A, B)
    print(f"x = {solution[0]:.2f}", f"\ny = {solution[1]:.2f}", f"\nz = {solution[2]:.2f}")
except np.linalg.LinAlgError:
    print("No solution exists for the given system of equations.")


> Solution
No solution exists for the given system of equations.


6. Determine if the vectors are linear combinations.
- We first transform the linear equations into an augmented matrix, then reduce it to its reduced row echelon form to determine its solution. Then we will be using a simple python code to check the solutions.

*6.a*
$$
\begin{align}
    v &= \begin{bmatrix}
        1 \\
        2
    \end{bmatrix} \\
    u_2 &= \begin{bmatrix}
        -1 \\
        3
    \end{bmatrix} \\
    u_3 &= \begin{bmatrix}
        2 \\
        -6
    \end{bmatrix} \\
\end{align}
$$

**Manual Solution**
- Transform the vectors into a linear equation of the form: $u_2x + u_3y = v$

$$
\begin{align}
    \begin{bmatrix}
        -1 \\
        3
    \end{bmatrix}(x) + \begin{bmatrix}
        2 \\
        -6
    \end{bmatrix}(y) &= \begin{bmatrix}
        1 \\
        2
    \end{bmatrix} \\
    \begin{bmatrix}
        (-1)x \\
        (3)x
    \end{bmatrix} + \begin{bmatrix}
        (2)y \\
        (-6)y
    \end{bmatrix} &= \begin{bmatrix}
        1 \\
        2
    \end{bmatrix} \\
    \begin{bmatrix}
        -x \\
        3x
    \end{bmatrix} + \begin{bmatrix}
        2y \\
        -6y
    \end{bmatrix} &= \begin{bmatrix}
        1 \\
        2
    \end{bmatrix}
\end{align}
$$
- This gives us the following systems of linear equations:
$$
    -x + 2y = 1 \\
    3x - 6y = 2
$$
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        -1 & 2 & | & 1 \\
        3 & -6 & | & 2
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        -1 & 2 & | & 1 \\
        3 & -6 & | & 2
    \end{bmatrix}
    \xrightarrow{-R_1}
    \begin{bmatrix}
        1 & -2 & | & -1 \\
        3 & -6 & | & 2
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & -2 & | & -1 \\
        3 & -6 & | & 2
    \end{bmatrix}
    \xrightarrow{R_2 - 3R_1}
    \begin{bmatrix}
        1 & -2 & | & -1 \\
        0 & 0 & | & 5
    \end{bmatrix}
\end{align}
$$

- There is inconsistencies in the last row since $0x + 0y =5$ is not possible, making this system have no solutions. $\therefore$ the vectors $v, u_2$ and $u_3$ are **NOT linear combinations** of each other.

**Pythonic Solution**

In [381]:
import numpy as np

# Coefficient matrix
A = np.array([[-1, 2], [3, -6]])

# Right-hand side column vector
B = np.array([1, 2])

print("> Solution")
try:
    solution = np.linalg.solve(A, B)
    print(f"x = {solution[0]:.2f}", f"\ny = {solution[1]:.2f}", f"\nz = {solution[2]:.2f}")
except np.linalg.LinAlgError:
    print("No solution exists for the given system of equations.")

> Solution
No solution exists for the given system of equations.


*6.b*
$$
\begin{align}
    v &= \begin{bmatrix}
        1 \\
        2 \\
        3
    \end{bmatrix} \\
    u_2 &= \begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix} \\
    u_3 &= \begin{bmatrix}
        0 \\
        1 \\
        1
    \end{bmatrix} \\
\end{align}
$$

**Manual Solution**
- Transform the vectors into a linear equation of the form: $u_2x + u_3y = v$
$$
\begin{align}
    \begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix}(x) + \begin{bmatrix}
        0 \\
        1 \\
        1
    \end{bmatrix}(y) &= \begin{bmatrix}
        1 \\
        2 \\
        3
    \end{bmatrix} \\
    \begin{bmatrix}
        (1)x \\
        (1)x \\
        (0)x
    \end{bmatrix} + \begin{bmatrix}
        (0)y \\
        (1)y \\
        (1)y
    \end{bmatrix} &= \begin{bmatrix}
        1 \\
        2 \\
        3
    \end{bmatrix} \\
    \begin{bmatrix}
        x \\
        x \\
        0
    \end{bmatrix} + \begin{bmatrix}
        0 \\
        y \\
        y
    \end{bmatrix} &= \begin{bmatrix}
        1 \\
        2 \\
        3
    \end{bmatrix}
\end{align}
$$
- This gives us the following systems of linear equations:
$$
    x = 1 \\
    x + y = 2 \\
    y = 3
$$
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & | & 1 \\
        1 & 1 & | & 2 \\
        0 & 1 & | & 3 \\
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & | & 1 \\
        1 & 1 & | & 2 \\
        0 & 1 & | & 3 \\
    \end{bmatrix}
    \xrightarrow{R_2 - R_1}
    \begin{bmatrix}
        1 & 0 & | & 1 \\
        0 & 1 & | & 1 \\
        0 & 1 & | & 3 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & | & 1 \\
        0 & 1 & | & 1 \\
        0 & 1 & | & 3 \\
    \end{bmatrix}
    \xrightarrow{R_3 - R_2}
    \begin{bmatrix}
        1 & 0 & | & 1 \\
        0 & 1 & | & 1 \\
        0 & 0 & | & 2 \\
    \end{bmatrix}
\end{align}
$$

- There is inconsistencies in the last row since $0x + 0y = 2$ is not possible, making this system have no solutions. $\therefore$ the vectors $v, u_2$ and $u_3$ are **NOT linear combinations** of each other.

**Pythonic Solution**

In [382]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 0], [1, 1], [0, 1]])

# Right-hand side column vector
B = np.array([1, 2, 3])

print("> Solution")
try:
    solution = np.linalg.solve(A, B)
    print(f"x = {solution[0]:.2f}", f"\ny = {solution[1]:.2f}", f"\nz = {solution[2]:.2f}")
except np.linalg.LinAlgError:
    print("No solution exists for the given system of equations.")

> Solution
No solution exists for the given system of equations.


*6.c*
$$
\begin{align}
    v &= \begin{bmatrix}
        3 \\
        1 \\
        -2
    \end{bmatrix} \\
    u_2 &= \begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix} \\
    u_3 &= \begin{bmatrix}
        0 \\
        1 \\
        1
    \end{bmatrix} \\
\end{align}
$$

**Manual Solution**
- Transform the vectors into a linear equation of the form: $u_2x + u_3y = v$
$$
\begin{align}
    \begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix}(x) + \begin{bmatrix}
        0 \\
        1 \\
        1
    \end{bmatrix}(y) &= \begin{bmatrix}
        3 \\
        1 \\
        -2
    \end{bmatrix} \\
    \begin{bmatrix}
        (1)x \\
        (1)x \\
        (0)x
    \end{bmatrix} + \begin{bmatrix}
        (0)y \\
        (1)y \\
        (1)y
    \end{bmatrix} &= \begin{bmatrix}
        3 \\
        1 \\
        -2
    \end{bmatrix} \\
    \begin{bmatrix}
        x \\
        x \\
        0
    \end{bmatrix} + \begin{bmatrix}
        0 \\
        y \\
        y
    \end{bmatrix} &= \begin{bmatrix}
        3 \\
        1 \\
        -2
    \end{bmatrix}
\end{align}
$$
- This gives us the following systems of linear equations:
$$
    x = 3 \\
    x + y = 1 \\
    y = -2
$$
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & | & 3 \\
        1 & 1 & | & 1 \\
        0 & 1 & | & -2 \\
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 0 & | & 3 \\
        1 & 1 & | & 1 \\
        0 & 1 & | & -2 \\
    \end{bmatrix}
    \xrightarrow{R_2 - R_1}
    \begin{bmatrix}
        1 & 0 & | & 3 \\
        0 & 1 & | & -2 \\
        0 & 1 & | & -2 \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & | & 3 \\
        0 & 1 & | & -2 \\
        0 & 1 & | & -2 \\
    \end{bmatrix}
    \xrightarrow{R_3 - R_2}
    \begin{bmatrix}
        1 & 0 & | & 3 \\
        0 & 1 & | & -2 \\
        0 & 0 & | & 0 \\
    \end{bmatrix}
\end{align}
$$

- The solution of the system would be $x = 3$ and $y = -2$, giving us the linear equation: $3u_2 - 2u_3 = v$. $\therefore$ the vectors $v, u_2$ and $u_3$ are **linear combinations** of each other.

**Pythonic Solution**

In [383]:
import numpy as np

# Coefficient matrix
A = np.array([[1, 0], [1, 1], [0, 1]])

# Right-hand side column vector
B = np.array([3, 1, -2])

solution = np.linalg.lstsq(A, B, rcond=None)[0]
print("> Solution")
print(f"x = {solution[0]:.2f}", f"\ny = {solution[1]:.2f}")

> Solution
x = 3.00 
y = -2.00


7. Show that the following vectors are a span:

*7.a*
$$
\begin{align}
    span \begin{pmatrix}
        \begin{bmatrix}
            1 \\
            1
        \end{bmatrix} \begin{bmatrix}
            1 \\
            -1
        \end{bmatrix}
    \end{pmatrix}
\end{align}
$$
- Transform the span into a linear equation:
$$
\begin{align}
    \begin{bmatrix}
        1 \\
        1
    \end{bmatrix}(x) + \begin{bmatrix}
        1 \\
        -1
    \end{bmatrix}(y) = \begin{bmatrix}
        a \\
        b
    \end{bmatrix} \\
    \begin{bmatrix}
        x \\
        x
    \end{bmatrix} + \begin{bmatrix}
        y \\
        -y
    \end{bmatrix} = \begin{bmatrix}
        a \\
        b
    \end{bmatrix}
\end{align}
$$

- This gives us the following systems of linear equations:
$$
    x + y = a \\
    x - y = b
$$
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & | & a \\
        1 & -1 & | & b \\
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & | & a \\
        1 & -1 & | & b \\
    \end{bmatrix}
    \xrightarrow{R_2 - R_1}
    \begin{bmatrix}
        1 & 1 & | & a \\
        0 & -2 & | & -a + b \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & | & a \\
        0 & -2 & | & -a + b \\
    \end{bmatrix}
    \xrightarrow{-\frac{R_2}{2}}
    \begin{bmatrix}
        1 & 1 & | & a \\
        0 & 1 & | & \frac{a - b}{2} \\
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & | & a \\
        0 & 1 & | & \frac{a - b}{2} \\
    \end{bmatrix}
    \xrightarrow{R_1 - R_2}
    \begin{bmatrix}
        1 & 0 & | & \frac{a + b}{2} \\
        0 & 1 & | & \frac{a + b}{2} \\
    \end{bmatrix}
\end{align}
$$

- The solution of the system would be $x = \frac{a + b}{2}$ and $y = \frac{a + b}{2}$. $\therefore$ the set of vectors **is a span**.

*7.b*
$$
\begin{align}
    span \begin{pmatrix}
        \begin{bmatrix}
            1 \\
            0 \\
            1
        \end{bmatrix} \begin{bmatrix}
            1 \\
            1 \\
            0
        \end{bmatrix} \begin{bmatrix}
            0 \\
            1 \\
            1
        \end{bmatrix}
    \end{pmatrix}
\end{align}
$$
- Transform the span into a linear equation:
$$
\begin{align}
    \begin{bmatrix}
        1 \\
        0 \\
        1
    \end{bmatrix}(x) + \begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix}(y) + \begin{bmatrix}
        0 \\
        1 \\
        1
    \end{bmatrix}(z) = \begin{bmatrix}
        a \\
        b \\
        c
    \end{bmatrix} \\
    \begin{bmatrix}
        x \\
        0 \\
        x
    \end{bmatrix} + \begin{bmatrix}
        y \\
        y \\
        0
    \end{bmatrix} + \begin{bmatrix}
        0 \\
        z \\
        z
    \end{bmatrix} = \begin{bmatrix}
        a \\
        b \\
        c
    \end{bmatrix}
\end{align}
$$

- This gives us the following systems of linear equations:
$$
    x + y = a \\
    y + z = b \\
    x + z = c
$$
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        1 & 0 & 1 & | & c
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        1 & 0 & 1 & | & c
    \end{bmatrix}
    \xrightarrow{R_3 - R_1}
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix}
    \xrightarrow{R_1 - R_2}
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix}
    \xrightarrow{R_3 + R_2}
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 2 & | & -a + b + c
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 2 & | & -a + b + c
    \end{bmatrix}
    \xrightarrow{\frac{R_3}{2}}
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & -\frac{a + b + c}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & -\frac{a + b + c}{2}
    \end{bmatrix}
    \xrightarrow{R_1 + R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{a - b + c}{2} \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & \frac{-a + b + c}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{a - b + c}{2} \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & \frac{-a + b + c}{2}
    \end{bmatrix}
    \xrightarrow{R_2 - R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{a - b + c}{2} \\
        0 & 1 & 0 & | & \frac{a + b - c}{2} \\
        0 & 0 & 1 & | & \frac{-a + b + c}{2}
    \end{bmatrix}
\end{align}
$$

- The solution of the system would be $x = \frac{a - b + c}{2}, y = \frac{a + b - c}{2}$ and $z = \frac{-a + b + c}{2}$. $\therefore$ the set of vectors **is a span**.

*7.c*
$$
\begin{align}
    span \begin{pmatrix}
        \begin{bmatrix}
            1 \\
            0 \\
            1
        \end{bmatrix} \begin{bmatrix}
            1 \\
            1 \\
            0
        \end{bmatrix} \begin{bmatrix}
            0 \\
            1 \\
            1
        \end{bmatrix}
    \end{pmatrix}
\end{align}
$$
- Transform the span into a linear equation:
$$
\begin{align}
    \begin{bmatrix}
        1 \\
        0 \\
        1
    \end{bmatrix}(x) + \begin{bmatrix}
        1 \\
        1 \\
        0
    \end{bmatrix}(y) + \begin{bmatrix}
        0 \\
        1 \\
        1
    \end{bmatrix}(z) = \begin{bmatrix}
        a \\
        b \\
        c
    \end{bmatrix} \\
    \begin{bmatrix}
        x \\
        0 \\
        x
    \end{bmatrix} + \begin{bmatrix}
        y \\
        y \\
        0
    \end{bmatrix} + \begin{bmatrix}
        0 \\
        z \\
        z
    \end{bmatrix} = \begin{bmatrix}
        a \\
        b \\
        c
    \end{bmatrix}
\end{align}
$$

- This gives us the following systems of linear equations:
$$
    x + y = a \\
    y + z = b \\
    x + z = c
$$
- Transform equations into an augmented matrix:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        1 & 0 & 1 & | & c
    \end{bmatrix}
\end{align}
$$
- Transform matrix into its reduce row echelon form:
$$
\begin{align}
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        1 & 0 & 1 & | & c
    \end{bmatrix}
    \xrightarrow{R_3 - R_1}
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 1 & 0 & | & a \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix}
    \xrightarrow{R_1 - R_2}
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & -1 & 1 & | & a + c
    \end{bmatrix}
    \xrightarrow{R_3 + R_2}
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 2 & | & -a + b + c
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 2 & | & -a + b + c
    \end{bmatrix}
    \xrightarrow{\frac{R_3}{2}}
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & -\frac{a + b + c}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & -1 & | & a - b \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & -\frac{a + b + c}{2}
    \end{bmatrix}
    \xrightarrow{R_1 + R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{a - b + c}{2} \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & \frac{-a + b + c}{2}
    \end{bmatrix} \\
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{a - b + c}{2} \\
        0 & 1 & 1 & | & b \\
        0 & 0 & 1 & | & \frac{-a + b + c}{2}
    \end{bmatrix}
    \xrightarrow{R_2 - R_3}
    \begin{bmatrix}
        1 & 0 & 0 & | & \frac{a - b + c}{2} \\
        0 & 1 & 0 & | & \frac{a + b - c}{2} \\
        0 & 0 & 1 & | & \frac{-a + b + c}{2}
    \end{bmatrix}
\end{align}
$$

- The solution of the system would be $x = \frac{a - b + c}{2}, y = \frac{a + b - c}{2}$ and $z = \frac{-a + b + c}{2}$. $\therefore$ the set of vectors **is a span**.

8. Show that the following vectors are linearly independent:

*8.a*
$$
\begin{align}
    \begin{bmatrix}
        3 \\
        -1 \\
        1 \\
        -1
    \end{bmatrix} \begin{bmatrix}
        -1 \\
        2 \\
        1 \\
        -1
    \end{bmatrix} \begin{bmatrix}
        1 \\
        1 \\
        3 \\
        1
    \end{bmatrix} \begin{bmatrix}
        -1 \\
        -1 \\
        1 \\
        3
    \end{bmatrix}
\end{align}
$$
- By definition, given a matrix $A$ with $n$ rows and $m$ columns, the vectors of A will be linearly dependent if $m > n$. Our given has $m = 4$ and $n = 4$ which makes $m = n$. $\therefore$ the vectors **are linearly independent**

*8.b*
$$
\begin{align}
    \begin{bmatrix}
        0 \\
        0 \\
        0 \\
        1
    \end{bmatrix} \begin{bmatrix}
        0 \\
        0 \\
        2 \\
        1
    \end{bmatrix} \begin{bmatrix}
        0 \\
        3 \\
        2 \\
        1
    \end{bmatrix} \begin{bmatrix}
        4 \\
        3 \\
        2 \\
        1
    \end{bmatrix}
\end{align}
$$
- By definition, given a matrix $A$ with $n$ rows and $m$ columns, the vectors of A will be linearly dependent if $m > n$. Our given has $m = 4$ and $n = 4$ which makes $m = n$. $\therefore$ the vectors **are linearly independent**

*8.c*
$$
\begin{align}
    \begin{bmatrix}
        1 \\
        -1 \\
        1 \\
        0
    \end{bmatrix} \begin{bmatrix}
        -1 \\
        1 \\
        0 \\
        1
    \end{bmatrix} \begin{bmatrix}
        1 \\
        0 \\
        1 \\
        -1
    \end{bmatrix} \begin{bmatrix}
        0 \\
        1 \\
        -1 \\
        1
    \end{bmatrix}
\end{align}
$$
- By definition, given a matrix $A$ with $n$ rows and $m$ columns, the vectors of A will be linearly dependent if $m > n$. Our given has $m = 4$ and $n = 4$ which makes $m = n$. $\therefore$ the vectors **are linearly independent**